# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/openbox/all/openbox.rbi
#
# openbox-0.5.1

module Openbox
  def database; end
  def runtime; end
  def self.database; end
  def self.runtime; end
end
class Openbox::Database
  def adapters; end
  def connect_mysql2; end
  def connect_pg; end
  def ensure_connection!; end
  def retry_in(timeout: nil); end
end
class Openbox::Runtime
  def groups; end
  def has?(*names); end
  def initialize(dependencies = nil); end
  def rails?; end
  def select(*names); end
end
class Openbox::Command < Thor::Group
  def before_execute; end
  def execute; end
end
module Openbox::Commands
end
class Openbox::Commands::Server < Openbox::Command
  def execute; end
end
class Openbox::Entrypoint < Thor
  def console(*args); end
  def migrate(*args); end
  def rake(*args); end
  def seed(*args); end
  def self.exit_on_failure?; end
  def server(*args); end
end
class Openbox::Commands::Rake < Openbox::Command
  def execute; end
end
class Openbox::Commands::Migrate < Openbox::Command
  def execute; end
end
class Openbox::Commands::Seed < Openbox::Command
  def execute; end
end
class Openbox::Commands::Console < Openbox::Command
  def execute; end
end
class Openbox::Commands::Sidekiq < Openbox::Command
  def execute; end
end
