# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tailwindcss-rails` gem.
# Please instead update this file by running `bin/tapioca gem tailwindcss-rails`.

module Tailwindcss; end
class Tailwindcss::Engine < ::Rails::Engine; end

# constants describing the upstream tailwindcss project
module Tailwindcss::Upstream; end

# rubygems platform name => upstream release filename
Tailwindcss::Upstream::NATIVE_PLATFORMS = T.let(T.unsafe(nil), Hash)

Tailwindcss::Upstream::VERSION = T.let(T.unsafe(nil), String)
Tailwindcss::VERSION = T.let(T.unsafe(nil), String)
