include:
  - remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/rails.yml
  - remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/swarm.yml

variables:
  RUBY_VERSION: 3.0.4
  SORBET_ENABLED: yes
  # Deploy
  DEPLOY_BASE_DOMAIN: basaltic.tw
  DEPLOY_DOMAIN: ne.basaltic.tw
  DEPLOY_STACK_FILE: stack.yml

bundler-audit:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_PIPELINE_SOURCE == 'schedule'

bundler-leak:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_PIPELINE_SOURCE == 'schedule'

yarn-audit:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_PIPELINE_SOURCE == 'schedule'

rubocop:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

brakeman:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

assets:precompile:
  needs:
    - rspec
    - brakeman
    - rubocop
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

docker:
  needs:
    - job: assets:precompile
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        LATEST_IMAGE: 'yes'
    - if: $CI_COMMIT_TAG

trivy:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'schedule'

deploy:
  extends: .deploy
  stage: deploy
  environment:
    name: production
  needs:
    - docker
  tags:
    - tyc
    - swarm
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        POSTGRES_DB: $PRODUCTION_POSTGRES_DB
        POSTGRES_USER: $PRODUCTION_POSTGRES_USER
        POSTGRES_PASSWORD: $PRODUCTION_POSTGRES_PASSWORD
