version: '3.8'

services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    deploy:
      placement:
        constraints:
          - node.role != manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
  application:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    environment:
      - AUTO_MIGRATION=yes
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
      - SECRET_KEY_BASE
      - RAILS_MASTER_KEY
      - SENTRY_DSN
    deploy:
      placement:
        constraints:
          - node.role != manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        # Hosts
        - "traefik.http.routers.${DEPLOY_NAME}-http.rule=Host(`${DEPLOY_DOMAIN}`)"
        - "traefik.http.routers.${DEPLOY_NAME}-http.entrypoints=web"
        - "traefik.http.routers.${DEPLOY_NAME}-http.middlewares=https-redirect"
        - "traefik.http.routers.${DEPLOY_NAME}-https.rule=Host(`${DEPLOY_DOMAIN}`)"
        - "traefik.http.routers.${DEPLOY_NAME}-https.entrypoints=websecure"
        - "traefik.http.routers.${DEPLOY_NAME}-https.tls=true"
        - "traefik.http.routers.${DEPLOY_NAME}-https.tls.certresolver=letsencrypt"
        - "traefik.http.routers.${DEPLOY_NAME}-https.tls.domains[0].sans=*.${DEPLOY_BASE_DOMAIN}"
        - "traefik.http.services.${DEPLOY_NAME}.loadbalancer.server.port=3000"
        - "traefik.http.services.${DEPLOY_NAME}.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.${DEPLOY_NAME}.loadbalancer.healthcheck.path=/status"
    networks:
      - net
      - traefik-public
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver_opts:
      type: "nfs"
      o: "addr=$NFS_SERVER,rw,async,vers=4"
      device: ":$NFS_VOLUME_PATH"

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
