# typed: true
# frozen_string_literal: true

require 'active_support/cache'
require 'active_support/core_ext/integer/time'
require 'bootsnap/setup'
require 'bundler/setup'
require 'capybara'
require 'cucumber'
require 'cucumber/rails'
require 'debug'
require 'debug/open_nonstop'
require 'devise/orm/active_record'
require 'dry/container/stub'
require 'factory_bot'
require 'faker'
require 'flipper/adapters/active_support_cache_store'
require 'rack-mini-profiler'
require 'rails/all'
require 'rspec/rails'
require 'shoulda/matchers'
require 'sidekiq/web'
require 'simplecov'
require 'simplecov-cobertura'
require 'view_component/test_helpers'
