# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LinkButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl LinkButtonComponent`.

class LinkButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
