# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `QuestItemComponent`.
# Please instead update this file by running `bin/tapioca dsl QuestItemComponent`.

class QuestItemComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
