# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TileComponent`.
# Please instead update this file by running `bin/tapioca dsl TileComponent`.

class TileComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
