register_allowlist:
  path: tmp/allowlist.txt
  spreadsheet_key:
game_data:
  spreadsheet_key:
  import:
    - repository: 'Map'
      fields: ['name']
      source: 'Map!A1:B'
    - repository: 'Area'
      fields: ['name', 'map_id', 'terrain']
      source: 'Area!A1:E'

