# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Cucumber::Rails::Database; end
module Sprockets::SassProcessor::Functions; end
module Turbo::Streams::ActionHelper; end
