# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Admin::Table::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Admin::Table::HeaderComponent`.

class Admin::Table::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
