# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Admin::AlertComponent`.
# Please instead update this file by running `bin/tapioca dsl Admin::AlertComponent`.

class Admin::AlertComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
