# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Admin::CardComponent`.
# Please instead update this file by running `bin/tapioca dsl Admin::CardComponent`.

class Admin::CardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
