# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Admin::FooterComponent`.
# Please instead update this file by running `bin/tapioca dsl Admin::FooterComponent`.

class Admin::FooterComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
