# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Admin::MainMenuGroupComponent`.
# Please instead update this file by running `bin/tapioca dsl Admin::MainMenuGroupComponent`.

class Admin::MainMenuGroupComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
