# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Admin::TableComponent`.
# Please instead update this file by running `bin/tapioca dsl Admin::TableComponent`.

class Admin::TableComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
