name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  rspec:
    name: RSpec
    uses: ./.github/workflows/test-action.yml
    with:
      command: bundle exec rspec

  cucumber:
    name: Cucumber
    uses: ./.github/workflows/test-action.yml
    with:
      command: bundle exec cucumber
