name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  rspec:
    name: RSpec
    uses: ./.github/workflows/test-action.yml
    with:
      command: bundle exec rspec

  cucumber:
    name: Cucumber
    uses: ./.github/workflows/test-action.yml
    env:
      SPREADSHEET_SERVICE_ACCOUNT: ${{ secret.SPREADSHEET_SERVICE_ACCOUNT }}
    with:
      command: |
        echo $SPREADSHEET_SERVICE_ACCOUNT > config/credentials/spreadsheet-service_account.json
        bundle exec cucumber
